export const MESSAGE = {
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    PHOTO_NOT_EXIST: 'Photo not exists',
    TO_BIG_PHOTO_FILE: 'File is to big',
    WRONG_FILE_FORMAT: 'wrong file format',
    USER_NOT_EXIST: 'user doesn\'t exists',
    UNAUTHORIZED: 'unauthorized',
    TOKEN_NOT_VALID: 'token not valid',
    LOGOUT_USER: 'logout user',
    CATEGORY_NOT_EXIST: 'Category is not exists',
    GENDER_CATEGORY_NOT_INCLUDE_CATEGORY: 'gender category is not includes category',
    GENDER_NOT_INCLUDE_GENDER_CATEGORY: 'gender is not includes genderCategory',
    PRODUCT_INFORMATION_NOT_EXIST: 'Product information is not exists',
    CATEGORY_EXIST: 'Category is already exists',
    GENDER_CATEGORY_EXIST: 'Gender category is already exists',
    GENDER_NOT_EXIST: 'Gender is not exists',
    GENDER_CATEGORY_NOT_EXIST: 'Gender category is not exists',
    PRODUCT_NOT_EXIST: 'Product is not exists',
    PRODUCT_SIZE_NOT_EXIST: 'Product size is not exists',
    PRODUCT_PHOTO_NOT_EXIST: 'Product photo is not exists',
    PRODUCT_SIZE_LIMIT: 'Product size limits 5 sizes',
    PRODUCT_PHOTOS_LIMIT: 'Product photo limits 5 photos',
    GENDER_EXIST: 'Gender is already not exists',
    PRODUCT_EXIST: 'Product is already not exists',
};
