export const MESSAGE = {
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    PHOTO_NOT_EXIST: 'Photo not exists',
    CATEGORY_NOT_EXIST: 'Category not exists',
    DISH_NOT_EXIST: 'Dish not exists',
    CATEGORY_IS_EXIST: 'Category is exists',
    VIDEO_NOT_EXIST: 'Video not exists',
    TO_BIG_PHOTO_FILE: 'File is to big',
    TO_BIG_VIDEO_FILE: 'File is to big',
    WRONG_FILE_FORMAT: 'wrong file format',
    POST_IS_EXIST: 'post title is exists',
    POST_NOT_EXIST: 'post doesn\'t exists',
    COMMENT_NOT_EXIST: 'comment doesn\'t exists',
    USER_NOT_EXIST: 'user doesn\'t exists',
    INCORRECT_AUTHOR: 'Incorrect author of the comment',
    UNAUTHORIZED: 'unauthorized',
    TOKEN_NOT_VALID: 'token not valid',
    LOGOUT_USER: 'logout user',
    USER_DOES_NOT_HAVE_ADMINISTRATOR_RIGHTS: 'User doesn\'t have administrator rights',
    NOT_USER: 'User is not exist',
};
