export * from './apiRouter';
export * from './authRouter';
export * from './categoryRouter';
export * from './genderRouter';
export * from './productRouter';
export * from './productInformationRouter';
export * from './productSizeRouter';
export * from './productPhotoRouter';
export * from './genderCategoryRouter';
