export * from './genderInterface';
export * from './categoryInterface';
export * from './productInterface';
export * from './paginationResponseInterface';
export * from './genderCategoryInterface';
export * from './authInterface';
export * from './productSizeInterface'
export * from './productPhotoInterface';
export * from './productInformationInterface';
