import dotenv from 'dotenv';

dotenv.config();

export const config = {
    PORT: process.env.PORT,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY || 'SECRET_ACCESS_KEY',
    SECRET_REFRESH_KEY: process.env.SECRET_REFRESH_KEY || 'SECRET_REFRESH_KEY',
    SECRET_ACTION_KEY: process.env.SECRET_ACTION_KEY || 'SECRET_ACTION_KEY',
    EXPIRES_IN_ACCESS: process.env.EXPIRES_IN_ACCESS || '30m',
    EXPIRES_IN_REFRESH: process.env.EXPIRES_IN_REFRESH || '30d',
    EXPIRES_IN_ACTION: process.env.EXPIRES_IN_ACTION || '1d',
    SECRET_ADMIN_EMAIL: process.env.SECRET_ADMIN_EMAIL,
    SECRET_MANAGER_EMAIL: process.env.SECRET_MANAGER_EMAIL,
    SECRET_ADMIN_PASSWORD: process.env.SECRET_ADMIN_PASSWORD,
    SECRET_MANAGER_PASSWORD: process.env.SECRET_MANAGER_PASSWORD,
    NO_REPLY_EMAIL: process.env.NO_REPLY_EMAIL,
    NO_REPLY_PASSWORD: process.env.NO_REPLY_PASSWORD,
};
